# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.synced_folder "../ansible", "/ansible", :owner=> 'vagrant', :mount_options => ["dmode=775,fmode=664"]

  # NAT DNS resolver
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # VirtualBox specific configurations
  config.vm.provider "virtualbox" do |vb|
    vb.name = "kubernetes"
    vb.gui = false
    vb.memory = "1024"
  end

  # Provision with inline shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y update
    sudo yum -y install epel-release
    sudo yum -y install ansible
    sudo -u vagrant ssh-keygen -f ~vagrant/.ssh/id_rsa -t rsa -b 4096 -N '' -C "vagrant@ericsson.com"
    sudo cat ~vagrant/.ssh/id_rsa.pub >> ~vagrant/.ssh/authorized_keys
    sudo -u vagrant chmod 640 ~vagrant/.ssh/authorized_keys
  SHELL
end
