---
- name: Kubernetes Master
  hosts: master
  remote_user: vagrant
  roles:
    - role: kubernetes-master

- name: Kubernetes Minion
  hosts: minion
  remote_user: vagrant
  roles:
    - role: kubernetes-minion

- name: Proxy Server
  hosts: proxy
  remote_user: vagrant
  roles:
    - role: haproxy
