#!/bin/bash

DISPLAY_NUMBER=$1
export DISPLAY=":$DISPLAY_NUMBER.0"

export SCREEN_WIDTH="1360"
export SCREEN_HEIGHT="1020"
export SCREEN_DEPTH="24"

export GEOMETRY="$SCREEN_WIDTH""x""$SCREEN_HEIGHT""x""$SCREEN_DEPTH"
