---
- name: install libexif
  yum: name=libexif
  sudo: true

- name: register chrome yum repo
  template: src=google-chrome.repo.j2 dest=/etc/yum.repos.d/google-chrome.repo owner=root group=root mode=0666
  sudo: true

- name: install google chrome
  yum: name=google-chrome-stable
  sudo: true

- name: download chromedriver
  get_url: url=http://chromedriver.storage.googleapis.com/{{chrome_driver_version}}/chromedriver_linux64.zip dest={{selenium_home}}/chromedriver-{{chrome_driver_version}}.zip
  sudo: true

- name: unarchive chromedriver
  unarchive: src={{selenium_home}}/chromedriver-{{chrome_driver_version}}.zip dest={{selenium_home}} mode=0755 copy=no
  sudo: true

- name: create link for chromedriver
  command: ln -fs {{selenium_home}}/chromedriver /usr/bin/chromedriver
  sudo: true
